from tkinter import *
import PIL.Image, PIL.ImageTk
root = Tk()

root.geometry("1255x1255")

bg = PIL.ImageTk.PhotoImage(PIL.Image.open("cbg.jpg"))
labelb = Label(root, image=bg)
labelb.place(x=0,y=0)
cards = LabelFrame(root, padx=2, pady=10)
cards.pack(padx=1,pady=10)

#img1 = PIL.ImageTk.PhotoImage(PIL.Image.open("uf.png")) 
#img2 = PIL.ImageTk.PhotoImage(PIL.Image.open("uf.png"))
img3 = PIL.ImageTk.PhotoImage(PIL.Image.open("uf.png")) 
#img4 = PIL.ImageTk.PhotoImage(PIL.Image.open("uf.png")) 
#img5 = PIL.ImageTk.PhotoImage(PIL.Image.open("uf.png")) 
#img6 = PIL.ImageTk.PhotoImage(PIL.Image.open("uf.png")) 
#img7 = PIL.ImageTk.PhotoImage(PIL.Image.open("uf.png")) 
#img8 = PIL.ImageTk.PhotoImage(PIL.Image.open("uf.png")) 
#img9 = PIL.ImageTk.PhotoImage(PIL.Image.open("uf.png")) 
img10 = PIL.ImageTk.PhotoImage(PIL.Image.open("10.png")) 
label = Label(cards,image=img3,padx=1,pady=1)
label2 = Label(cards,image=img3,padx=1,pady=1)
label3 = Label(cards,image=img3,padx=1,pady=1)
label4 = Label(cards,image=img3,padx=1,pady=1)
label5 = Label(cards,image=img3,padx=1,pady=1)
label6 = Label(cards,image=img3,padx=1,pady=1)
label7 = Label(cards,image=img3,padx=1,pady=1)
label8 = Label(cards,image=img3,padx=1,pady=1)
label9 = Label(cards,image=img3,padx=1,pady=1)
label10 = Label(cards,image=img10,padx=1,pady=1)
label.grid(row=0,column=0)
label2.grid(row=0,column=1)
label3.grid(row=0,column=2)
label4.grid(row=0,column=3)
label5.grid(row=0,column=4)
label6.grid(row=0,column=5)
label7.grid(row=0,column=6)
label8.grid(row=0,column=7)
label9.grid(row=0,column=8)
label10.grid(row=0,column=9)

root.mainloop()

